### ISSUE TITLE
Make /revive replenish your food and drink as well

### ISSUE THREAD

**Issue by Jordan-Cache** [Qbox-project/qbx-adminmenu#16]
### The problem

Currently using the /revive admin command does not replenish your vitals.

### Ideal solution

Make the /revive command replenish all vitals and stats (ie. food, drink, stress, etc)

**Comment by Manason** [comment]
What does reviving have to do with food, drink, or stress? They seem like separate concepts to me.

**Comment by Jordan-Cache** [comment]
Its a feature in QBCore and as admin it is nice having the one command to fix everything about the character, not just death.

**Comment by ChatDisabled** [comment]
@Manason it always was part of the revive command. Matter of fact still tested and still is. Did you trigger the command in a specific way perhaps?


https://github.com/Qbox-project/qbx-adminmenu/assets/44729807/871bc821-fbb3-4b26-9e2a-aff4d82c3182
